name: .NET

env:
  "ML_MODEL_VERSION": "0.1.0-b8e1e1a"
  "ML_MODEL_URI": https://github.com/igoran/dnc-mlops-model-training/releases/download/0.1.0-b8e1e1a/0.1.0-b8e1e1a.zip
  "PULUMI_STACK_NAME": igoran/infra/dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  repository_dispatch:
    types: [model-created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Payload Data
      run: |
        echo ${{ github.event.client_payload.message.ML_MODEL_VERSION }}
        echo ${{ github.event.client_payload.message.ML_MODEL_URI }}
      env:
        ML_MODEL_VERSION: ${{ github.event.client_payload.message.ML_MODEL_VERSION }}
        ML_MODEL_URI: ${{ github.event.client_payload.message.ML_MODEL_URI }}
    - uses: actions/checkout@v2
      name: Checkout unshallow
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: ml
    - name: Build
      run: dotnet build ml/ml.sln --configuration Release --no-restore      
    - name: Test
      run: dotnet test ml/Predictor.Tests/Predictor.Tests.csproj --configuration Release --no-build --verbosity normal
      env:
        ML_MODEL_URI: ${{ env.ML_MODEL_URI }}
    - name: Publish
      run: dotnet publish ml/Predictor/Predictor.csproj --configuration Release     
    - name: Pulumi - Setup CLI
      run: |
        curl https://get.pulumi.com | bash
        echo "::add-path::$HOME/.pulumi/bin/"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Pulumi - Init new project by current SHA commit
      working-directory: ./infra
      run: |
        pulumi stack select ${{ env.PULUMI_STACK_NAME }} --non-interactive --create
        pulumi config set azure:location westeurope
        pulumi config set azure:clientId ${{ secrets.AZURE_CLIENT_ID }} 
        pulumi config set azure:clientSecret ${{ secrets.AZURE_SECRET }} --secret  
        pulumi config set azure:tenantId ${{ secrets.AZURE_TENANT_ID }}  
        pulumi config set azure:subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        pulumi up --non-interactive --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
